repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.0

  hooks:
    # - id: ruff
    #   name: linter
    #   types: [python]

    - id: ruff-format
      name: general formatter
      types: [python]

    - id: ruff
      name: import reformatter
      args: ["--select", "I", "--fix"]  # Focus on import reformatting and auto-fix
      types: [python]
