site_name: gp-retouch documentation
site_description: Documentation for the gp-retouch package
repo_url: https://github.com/emilioMaddalena/gp-retouch
site_url: https://emiliomaddalena.github.io/gp-retouch/
repo_name: emilioMaddalena/gp-retouch

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [gp_retouch]  # Scan the main package directory
          options:
            show_source: true
            docstring_style: google
            show_if_no_docstring: true
            separate_signature: true
            show_signature_annotations: true
            
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference:
    - Image: api/image.md
    - Image Processor: api/image_processor.md
  - Contributing: contributing.md