name: docs

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: uv sync --all-extras
      
      - name: Install the project
        run: |
          uv pip install -e .
          
      - name: Install mkdocs
        run: uv pip install mkdocs-material mkdocs-autorefs mkdocstrings[python]
      
      - name: Build docs
        run: uv run mkdocs build --verbose
      
      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
